### ISSUE TITLE
初始化的时候报的错，看源码并没有什么问题哦

### ISSUE THREAD

**Issue by YLAndsoft** [saiwu-bigkoo/Android-AlertView#38]
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setLayoutParams(android.view.ViewGroup$LayoutParams)' on a null object reference
        at com.bigkoo.alertview.AlertView.initViews(AlertView.java:132)
        at com.bigkoo.alertview.AlertView.<init>(AlertView.java:88)
        at com.wtkj.road.views.activity.EventDetailsActivity$1.onClick(EventDetailsActivity.java:126)
        at android.view.View.performClick(View.java:5773)
        at android.view.View$PerformClick.run(View.java:23035)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:232)
        at android.app.ActivityThread.main(ActivityThread.java:6802)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1103)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)

**Comment by saiwu-bigkoo** [comment]
空指针

**Comment by YLAndsoft** [comment]
contentContainer.setLayoutParams(params);什么情况下contentContainer会是空呢？我检查了，资源文件都依赖下来了.不可能会出现找不到id的情况喔. @saiwu-bigkoo
